/**
 * SafetyNet Child Web Application configuration.
 *
 * This project is configured for the Firebase Web SDK and is intended to use
 * Firebase Authentication plus Realtime Database on the Spark free tier.
 */

/**
 * Firebase configuration for the SafetyNet Child web app.
 *
 * These values are safe for browser-side initialization with the Firebase Web
 * SDK. Never place Admin SDK credentials or service account keys in client code.
 */
const firebaseConfig = {
  apiKey: "AIzaSyBBpVZwPcWTi7pUeNQBfUXcXDwoQV4a6sE",
  authDomain: "safetynet-61628-f0cd3.firebaseapp.com",
  projectId: "safetynet-61628-f0cd3",
  storageBucket: "safetynet-61628-f0cd3.firebasestorage.app",
  messagingSenderId: "835913186774",
  appId: "1:835913186774:web:0c2710eb0980539376b877",
  databaseURL: "https://safetynet-61628-f0cd3-default-rtdb.firebaseio.com"
};

/**
 * Application-wide configuration for the child-facing web experience.
 *
 * Shared feature flags and UI settings live here so behavior stays consistent
 * across modules.
 */
const APP_CONFIG = {
  name: "SafetyNet Child",
  version: "1.0.0",
  environment: "development", // development | production

  // Feature flags for incremental rollout and future expansion.
  features: {
    sos: true,
    quickContacts: true,
    emergencyHelpline: true,
    parentLinking: true,
    alertHistory: true,
    geofencing: false,
    safeZones: false
  },

  // Shared UI timing and list-size controls.
  ui: {
    maxAlertHistory: 50,
    autoRefreshInterval: 30000,
    sosHoldDuration: 2000
  },

  hardware: {
    heartbeatTimeoutMs: 120000,
    alertCooldownMs: 10000,
    screamThreshold: 75
  },

  // Shared linking settings used with the parent dashboard.
  linking: {
    otpLength: 6,
    requestExpiryMs: 300000
  },

  // Emergency helpline numbers for India.
  emergencyNumbers: [
    { name: "Police", number: "100", icon: "\uD83D\uDE93" },
    { name: "Ambulance", number: "102", icon: "\uD83D\uDE91" },
    { name: "Fire", number: "101", icon: "\uD83D\uDE92" },
    { name: "Women Helpline", number: "1091", icon: "\uD83D\uDC6E\u200D\u2640\uFE0F" },
    { name: "Child Helpline", number: "1098", icon: "\uD83E\uDDD2" },
    { name: "Emergency", number: "112", icon: "\uD83C\uDD98" }
  ]
};

/**
 * Canonical Realtime Database node names.
 *
 * Centralizing these names helps avoid typos and keeps data access patterns
 * consistent as the application grows.
 */
const COLLECTIONS = {
  USERS: "users",
  CHILDREN: "children",
  PARENTS: "parents",
  ALERTS: "alerts",
  DEVICES: "devices",
  DEVICE_STATUS: "deviceStatus",
  RELATIONSHIPS: "relationships",
  LINK_REQUESTS: "linkRequests",
  CONTACTS: "quickContacts",
  LOCATIONS: "locations",
  NOTIFICATIONS: "notifications"
};

/**
 * Supported alert types generated by device sensors or manual actions.
 */
const ALERT_TYPES = {
  SOS: "sos",
  FALL: "fall",
  SCREAM: "scream",
  MANUAL: "manual"
};

/**
 * Lifecycle states for alerts as they move through the response flow.
 */
const ALERT_STATUS = {
  ACTIVE: "active",
  ACKNOWLEDGED: "acknowledged",
  RESOLVED: "resolved",
  CANCELLED: "cancelled"
};

export { firebaseConfig, APP_CONFIG, COLLECTIONS, ALERT_TYPES, ALERT_STATUS };
